### ISSUE TITLE
Client crash when hitting Connect multiple times at downloading files stage

### ISSUE THREAD

**Issue by Juesto** [BZFlag-Dev/bzflag#128]
speedy computer/internet makes it harder to reproduce
potentially happening on all platforms
STR:
try to connect again while the previous connection reads preparing world, it will crash as soon the game is "loaded"

stack trace points to player.h's return id; (line 361) which breakpoints revealed it comes from playing.cxx line 2831. a memory corruption was believed but there isn't any. tested on a pair of laptops.

EDIT: turns out these stacktraces come from failing to abort when downloading files/textures with automatic downloads on.

**Comment by blast007** [comment]
As of yet, I've been unable to reproduce the crash.  However, a reasonably easy workaround would be to just disable the Connect option while the client is in the middle of connecting to a server.

**Comment by allejo** [comment]
Because it can be days or months before someone looks at this issue, let's avoid forcing people to search through IRC logs. Either copy/paste the relevant conversation on here or describe the steps you took to reproduce this issue.

**Comment by Juesto** [comment]
@allejo fixed, i meant that when i said "will complete later"

**Comment by blast007** [comment]
This may be an issue specific to servers running maps that use drawInfo objects, which if true is why I wasn't able to reproduce it before.  Here's the valgrind output of me spamming the connect button on PlanetMofo on Linux:
```
==78462== Invalid read of size 8
==78462==    at 0x2EC298: MeshDrawInfo::updateAnimation(double) (MeshDrawInfo.cxx:606)
==78462==    by 0x2408F7: World::updateAnimations(float) (World.cxx:583)
==78462==    by 0x2812D5: playingLoop() (playing.cxx:7279)
==78462==    by 0x283332: startPlaying(BzfDisplay*, SceneRenderer&) (playing.cxx:7773)
==78462==    by 0x257833: main (bzflag.cxx:1404)
==78462==  Address 0x3e59bd60 is 256 bytes inside a block of size 264 free'd
==78462==    at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:584)
==78462==    by 0x2E3437: MeshObstacle::~MeshObstacle() (MeshObstacle.cxx:304)
==78462==    by 0x2E3473: MeshObstacle::~MeshObstacle() (MeshObstacle.cxx:306)
==78462==    by 0x303ABA: GroupDefinition::clear() (ObstacleMgr.cxx:729)
==78462==    by 0x304B0E: GroupDefinitionMgr::clear() (ObstacleMgr.cxx:1038)
==78462==    by 0x23EEBA: World::~World() (World.cxx:96)
==78462==    by 0x24873E: WorldBuilder::~WorldBuilder() (WorldBuilder.cxx:39)
==78462==    by 0x26402B: joinGame() (playing.cxx:524)
==78462==    by 0x1B5389: JoinMenu::execute() (JoinMenu.cxx:255)
==78462==    by 0x1CC131: MenuDefaultKey::keyPress(BzfKeyEvent const&) (MenuDefaultKey.cxx:47)
==78462==    by 0x1AEAED: HUDui::keyPress(BzfKeyEvent const&) (HUDui.cxx:45)
==78462==    by 0x2652C6: doKey(BzfKeyEvent const&, bool) (playing.cxx:893)
==78462==  Block was alloc'd at
==78462==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==78462==    by 0x2E541F: MeshObstacle::unpack(void const*) (MeshObstacle.cxx:803)
==78462==    by 0x30410A: GroupDefinition::unpack(void const*) (ObstacleMgr.cxx:867)
==78462==    by 0x30504D: GroupDefinitionMgr::unpack(void const*) (ObstacleMgr.cxx:1152)
==78462==    by 0x2489FE: WorldBuilder::unpack(void const*) (WorldBuilder.cxx:109)
==78462==    by 0x268BAA: loadCachedWorld() (playing.cxx:1738)
==78462==    by 0x268E35: WorldDownLoader::start(char*) (playing.cxx:1778)
==78462==    by 0x26A3FB: handleServerMessage(bool, unsigned short, unsigned short, void const*) (playing.cxx:2068)
==78462==    by 0x27101D: doMessages() (playing.cxx:3447)
==78462==    by 0x281942: playingLoop() (playing.cxx:7384)
==78462==    by 0x283332: startPlaying(BzfDisplay*, SceneRenderer&) (playing.cxx:7773)
==78462==    by 0x257833: main (bzflag.cxx:1404)
==78462== 
==78462== Invalid read of size 8
==78462==    at 0x2453C6: MeshDrawInfo::isCopy() const (MeshDrawInfo.h:168)
==78462==    by 0x2EC0D5: MeshDrawInfo::getDrawMgr() const (MeshDrawInfo.cxx:563)
==78462==    by 0x240814: World::freeMeshDrawMgrs() (World.cxx:566)
==78462==    by 0x23ED9C: World::~World() (World.cxx:81)
==78462==    by 0x268B81: loadCachedWorld() (playing.cxx:1735)
==78462==    by 0x268E35: WorldDownLoader::start(char*) (playing.cxx:1778)
==78462==    by 0x26A3FB: handleServerMessage(bool, unsigned short, unsigned short, void const*) (playing.cxx:2068)
==78462==    by 0x27101D: doMessages() (playing.cxx:3447)
==78462==    by 0x281942: playingLoop() (playing.cxx:7384)
==78462==    by 0x283332: startPlaying(BzfDisplay*, SceneRenderer&) (playing.cxx:7773)
==78462==    by 0x257833: main (bzflag.cxx:1404)
==78462==  Address 0x3e59bc60 is 480 bytes inside an unallocated block of size 1,360 in arena "client"
==78462== 
==78462== Invalid read of size 8
==78462==    at 0x2EC0E5: MeshDrawInfo::getDrawMgr() const (MeshDrawInfo.cxx:564)
==78462==    by 0x240814: World::freeMeshDrawMgrs() (World.cxx:566)
==78462==    by 0x23ED9C: World::~World() (World.cxx:81)
==78462==    by 0x268B81: loadCachedWorld() (playing.cxx:1735)
==78462==    by 0x268E35: WorldDownLoader::start(char*) (playing.cxx:1778)
==78462==    by 0x26A3FB: handleServerMessage(bool, unsigned short, unsigned short, void const*) (playing.cxx:2068)
==78462==    by 0x27101D: doMessages() (playing.cxx:3447)
==78462==    by 0x281942: playingLoop() (playing.cxx:7384)
==78462==    by 0x283332: startPlaying(BzfDisplay*, SceneRenderer&) (playing.cxx:7773)
==78462==    by 0x257833: main (bzflag.cxx:1404)
==78462==  Address 0x3e59bca8 is 552 bytes inside an unallocated block of size 1,360 in arena "client"
==78462== 
==78462== Invalid write of size 8
==78462==    at 0x2453E6: MeshDrawInfo::setDrawMgr(MeshDrawMgr*) (MeshDrawInfo.h:172)
==78462==    by 0x240842: World::freeMeshDrawMgrs() (World.cxx:568)
==78462==    by 0x23ED9C: World::~World() (World.cxx:81)
==78462==    by 0x268B81: loadCachedWorld() (playing.cxx:1735)
==78462==    by 0x268E35: WorldDownLoader::start(char*) (playing.cxx:1778)
==78462==    by 0x26A3FB: handleServerMessage(bool, unsigned short, unsigned short, void const*) (playing.cxx:2068)
==78462==    by 0x27101D: doMessages() (playing.cxx:3447)
==78462==    by 0x281942: playingLoop() (playing.cxx:7384)
==78462==    by 0x283332: startPlaying(BzfDisplay*, SceneRenderer&) (playing.cxx:7773)
==78462==    by 0x257833: main (bzflag.cxx:1404)
==78462==  Address 0x3e59bca8 is 552 bytes inside an unallocated block of size 1,360 in arena "client"
==78462==
```

And on Windows, attached to the debugger, I'm getting "Exception thrown: read access violation. this->animInfo was 0xDDDDDDDD" inside MeshDrawInfo::updateAnimation() and the following backtrace:
```
>	bzflag.exe!MeshDrawInfo::updateAnimation(double time) Line 608	C++
 	bzflag.exe!World::updateAnimations(float dt) Line 584	C++
 	bzflag.exe!playingLoop() Line 7282	C++
 	bzflag.exe!startPlaying(BzfDisplay * _display, SceneRenderer & renderer) Line 7775	C++
 	bzflag.exe!SDL_main(int argc, char * * argv) Line 1404	C++
 	bzflag.exe!main_getcmdline() Line 80	C
 	bzflag.exe!WinMain(HINSTANCE__ * hInst, HINSTANCE__ * hPrev, char * szCmdLine, int sw) Line 110	C
```

**Comment by Juesto** [comment]
addendum:
the player stacktrace i was getting is the same issue but the wrong stacktrace
blast found out that one was 0xFEEFEE which is another magic number

**Comment by Zehra** [comment]
For additional history. This bug has been covered in the forums before.
**[Glitch when connecting to server](https://forums.bzflag.org/viewtopic.php?t=19051)**
by `Mopar Madness` on `Jun 27, 2015`
>If you start to connect to one server, but immediately go into the server list and select another server and then try to connect to that 2nd server as well while the 1st server is still loading, the game will load the map from the 1st server and the player list from the 2nd server, then about a second later crash to desktop. Not a priority to fix at all, but just kind of a cool quirky bug I figured should be made known! :D

It may possibly be related to other crashes with connecting to servers, but I'd be hesitant to say that is the case.

**Comment by ODelusion** [comment]
Spray and pray here, but my guesses.

For the server connect issue, you might try simply wailing away on the return key while joining.

Problems saving drawinfo possibly caused by the drawinfo not being properly created in the first place. Debugging of drawinfo is not perfect when loaded into the server. Buggy "regular" geometry almost always results in a stop, and refuses to load into bzfs. In regular geometry, non-planar faces and isolated vertices have been the only errors I've been able to get past bzfs. Buggy drawinfo will also result in a stop, but only on syntax errors. You can get some pretty wild geometry (as drawinfo) to load into bzfs. It will accept pretty much anything.
Drawinfo is not exposed to collision detection, so it makes sense that it needs less error detection, but that does not explain improper /saveworld behavior.

Modeltool's "bounding" option never worked properly for me, and in my world files I define invisible "regular" objects and drawinfo which occupies the same space, as separate objects.  Maybe the map maker is using "bounding" in their obj conversion which results in drawinfo and regular geometry combined into a single bzw object?
I would be interested to know if this is one of my files that refuses to save.

**Comment by Juesto** [comment]
reproduced on HEAD as of dec 8 2024, i think it's still very inconsistent. this happened with a debug build connecting to louman city map
```
(4ff4.10f4): C++ EH exception - code e06d7363 (first chance)
(4ff4.10f4): C++ EH exception - code e06d7363 (!!! second chance !!!)
eax=0019a7c8 ebx=00210000 ecx=00000003 edx=00000000 esi=5c0e15a8 edi=0019a860
eip=775e0f22 esp=0019a7c8 ebp=0019a820 iopl=0         nv up ei pl nz ac po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00200212
KERNELBASE!RaiseException+0x62:
775e0f22 8b4c2454        mov     ecx,dword ptr [esp+54h] ss:002b:0019a81c=a1b214e3
0:000> kp
 # ChildEBP RetAddr  
00 0019a820 5c0e97a9 KERNELBASE!RaiseException+0x62
01 0019a874 008538fc VCRUNTIME140D!_CxxThrowException(void * pExceptionObject = 0x0019a884, struct _s__ThrowInfo * pThrowInfo = 0x0097847c)+0xa9 [d:\agent\_work\1\s\src\vctools\crt\vcruntime\src\eh\throw.cpp @ 133] 
02 0019a890 008508a9 bzflag!__scrt_throw_std_bad_array_new_length(void)+0x1c [d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\heap\throw_bad_alloc.cpp @ 41] 
03 0019a89c 00851e3c bzflag!operator new(unsigned int size = 0xffffffff)+0x39 [d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\heap\new_scalar.cpp @ 46] 
04 0019a8a8 00541eff bzflag!operator new[](unsigned int size = 0xffffffff)+0xc [d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\heap\new_array.cpp @ 28] 
05 0019a910 0053e771 bzflag!ScoreboardRenderer::newSortedList(int sortType = 0n0, bool obsLast = true, int * _numPlayers = 0x00000000)+0x6f [z:\bzflag\src\bzflag\scoreboardrenderer.cxx @ 948] 
06 0019a934 004b29b6 bzflag!ScoreboardRenderer::getLeader(class std::basic_string<char,std::char_traits<char>,std::allocator<char> > * label = 0x0019aa98 "Leader ")+0x91 [z:\bzflag\src\bzflag\scoreboardrenderer.cxx @ 889] 
07 0019aacc 004b288a bzflag!Roaming::buildRoamingLabel(void)+0xc6 [z:\bzflag\src\bzflag\roaming.cxx @ 250] 
08 0019aaf4 004b255f bzflag!Roaming::changeTarget(Roaming::RoamingTarget target = next (0n0), int explicitIndex = 0n0)+0x15a [z:\bzflag\src\bzflag\roaming.cxx @ 214] 
09 0019ab08 005769e5 bzflag!Roaming::setMode(Roaming::RoamingView newView = roamViewFree (0n1))+0x7f [z:\bzflag\src\bzflag\roaming.cxx @ 76] 
0a 0019ada8 0057dded bzflag!enteringServer(void * buf = 0x0019c7d1)+0x435 [z:\bzflag\src\bzflag\playing.cxx @ 5072] 
0b 0019c76c 005830cb bzflag!handleServerMessage(bool human = true, unsigned short code = 0x6170, unsigned short len = 0xab, void * msg = 0x0019c7d1)+0x132d [z:\bzflag\src\bzflag\playing.cxx @ 2289] 
0c 0019cbe4 0058b9d5 bzflag!doMessages(void)+0xfb [z:\bzflag\src\bzflag\playing.cxx @ 3551] 
0d 0019d54c 0056f22e bzflag!playingLoop(void)+0x15c5 [z:\bzflag\src\bzflag\playing.cxx @ 7500] 
0e 0019e71c 0046ecf3 bzflag!startPlaying(class BzfDisplay * _display = 0x0324d2c0, class SceneRenderer * renderer = 0x009ad990)+0x136e [z:\bzflag\src\bzflag\playing.cxx @ 7891] 
0f 0019feb8 00855656 bzflag!SDL_main(int argc = 0n4, char ** argv = 0x00a187a8)+0x3273 [z:\bzflag\src\bzflag\bzflag.cxx @ 1404] 
10 0019fee4 008554d8 bzflag!main_getcmdline(void)+0x156 [z:\bzflag-dependencies\src\sdl2\src\main\windows\sdl_windows_main.c @ 80] 
11 0019feec 0085343e bzflag!WinMain(struct HINSTANCE__ * hInst = 0x00400000, struct HINSTANCE__ * hPrev = 0x00000000, char * szCmdLine = 0x009f4f65 "-window 1280x960 -dddd", int sw = 0n10)+0x8 [z:\bzflag-dependencies\src\sdl2\src\main\windows\sdl_windows_main.c @ 110] 
12 0019ff04 008532d7 bzflag!invoke_main(void)+0x1e [d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 107] 
13 0019ff60 0085316d bzflag!__scrt_common_main_seh(void)+0x157 [d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288] 
14 0019ff68 008534b8 bzflag!__scrt_common_main(void)+0xd [d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 331] 
15 0019ff70 7628fcc9 bzflag!WinMainCRTStartup(void)+0x8 [d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_winmain.cpp @ 17] 
16 0019ff80 77a1809e KERNEL32!BaseThreadInitThunk+0x19
17 0019ffdc 77a1806e ntdll!__RtlUserThreadStart+0x2f
18 0019ffec 00000000 ntdll!_RtlUserThreadStart+0x1b
```

**Comment by ODelusion** [comment]
Might be easier to reproduce if you set your computer's key repeat rate to begin repeating quickly and  repeat quickly, then hold down the return key while joining.
I don't think it has anything to do with the map file. 
This issue's history goes back farther than 2018. Might find it on source forge. It might have even been fixed at some point, only to return.

**Comment by Juesto** [comment]
interesting, and oddly enough this isn't fixed after tupone going through all the possible gotchas in the math code and stuff like that
drawInfo maps do seem to contribute to the issue as blast said

**Comment by ODelusion** [comment]
that might be because drawinfo typically takes much longer to download, giving the bug more time to occur

**Comment by atupone** [comment]
It Is fixed, unless someone prove it is not. 2.4 head

**Comment by Juesto** [comment]
crashed with the same reproduction steps
```
(4b58.4f14): Access violation - code c0000005 (first chance)
eax=00000000 ebx=0023a000 ecx=00000000 edx=008d7b2c esi=0019cbac edi=0019cb94
eip=00460c81 esp=0019cb48 ebp=0019cb4c iopl=0         nv up ei pl nz na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00210206
bzflag!World::getMaxShots+0x11:
00460c81 8b4014          mov     eax,dword ptr [eax+14h] ds:002b:00000014=????????
0:000> kp
 # ChildEBP RetAddr  
00 0019cb4c 0055cfa3 bzflag!World::getMaxShots(void)+0x11 [z:\bzflag\src\bzflag\world.h @ 312] 
01 0019cba0 005571f9 bzflag!LocalPlayer::doUpdate(float dt = 0.1000000015)+0x53 [z:\bzflag\src\bzflag\localplayer.cxx @ 100] 
02 0019cbe0 0058b3d6 bzflag!BaseLocalPlayer::update(float inputDT = -1)+0x709 [z:\bzflag\src\bzflag\baselocalplayer.cxx @ 112] 
03 0019d54c 0056f22e bzflag!playingLoop(void)+0xfa6 [z:\bzflag\src\bzflag\playing.cxx @ 7365] 
04 0019e71c 0046ecf3 bzflag!startPlaying(class BzfDisplay * _display = 0x031804c8, class SceneRenderer * renderer = 0x009ad990)+0x136e [z:\bzflag\src\bzflag\playing.cxx @ 7892] 
05 0019feb8 00855656 bzflag!SDL_main(int argc = 0n4, char ** argv = 0x00ca4d28)+0x3273 [z:\bzflag\src\bzflag\bzflag.cxx @ 1404] 
06 0019fee4 008554d8 bzflag!main_getcmdline(void)+0x156 [z:\bzflag-dependencies\src\sdl2\src\main\windows\sdl_windows_main.c @ 80] 
07 0019feec 0085343e bzflag!WinMain(struct HINSTANCE__ * hInst = 0x00400000, struct HINSTANCE__ * hPrev = 0x00000000, char * szCmdLine = 0x00c7503d "-ddd -window 1280x960", int sw = 0n10)+0x8 [z:\bzflag-dependencies\src\sdl2\src\main\windows\sdl_windows_main.c @ 110] 
08 0019ff04 008532d7 bzflag!invoke_main(void)+0x1e [d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 107] 
09 0019ff60 0085316d bzflag!__scrt_common_main_seh(void)+0x157 [d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288] 
0a 0019ff68 008534b8 bzflag!__scrt_common_main(void)+0xd [d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 331] 
0b 0019ff70 767afcc9 bzflag!WinMainCRTStartup(void)+0x8 [d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_winmain.cpp @ 17] 
0c 0019ff80 76ff809e KERNEL32!BaseThreadInitThunk+0x19
0d 0019ffdc 76ff806e ntdll!__RtlUserThreadStart+0x2f
0e 0019ffec 00000000 ntdll!_RtlUserThreadStart+0x1b
```

**Comment by Juesto** [comment]
again after the fix to the last stacktrace
```
(83e0.4c0c): Access violation - code c0000005 (first chance)
eax=00000000 ebx=0037b000 ecx=00000000 edx=008d7b2c esi=0019cbac edi=0019cb94
eip=00460c81 esp=0019cb48 ebp=0019cb4c iopl=0         nv up ei ng nz na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00210286
bzflag!World::getMaxShots+0x11:
00460c81 8b4014          mov     eax,dword ptr [eax+14h] ds:002b:00000014=????????
0:000> kp
 # ChildEBP RetAddr  
00 0019cb4c 0055cfa3 bzflag!World::getMaxShots(void)+0x11 [z:\bzflag\src\bzflag\world.h @ 312] 
01 0019cba0 005571f9 bzflag!LocalPlayer::doUpdate(float dt = 0.1000000015)+0x53 [z:\bzflag\src\bzflag\localplayer.cxx @ 100] 
02 0019cbe0 0058b3e3 bzflag!BaseLocalPlayer::update(float inputDT = -1)+0x709 [z:\bzflag\src\bzflag\baselocalplayer.cxx @ 112] 
03 0019d54c 0056f22e bzflag!playingLoop(void)+0xfb3 [z:\bzflag\src\bzflag\playing.cxx @ 7365] 
04 0019e71c 0046ecf3 bzflag!startPlaying(class BzfDisplay * _display = 0x00de58d0, class SceneRenderer * renderer = 0x009ad990)+0x136e [z:\bzflag\src\bzflag\playing.cxx @ 7892] 
05 0019feb8 00855656 bzflag!SDL_main(int argc = 0n4, char ** argv = 0x00cfe8d8)+0x3273 [z:\bzflag\src\bzflag\bzflag.cxx @ 1404] 
06 0019fee4 008554d8 bzflag!main_getcmdline(void)+0x156 [z:\bzflag-dependencies\src\sdl2\src\main\windows\sdl_windows_main.c @ 80] 
07 0019feec 0085343e bzflag!WinMain(struct HINSTANCE__ * hInst = 0x00400000, struct HINSTANCE__ * hPrev = 0x00000000, char * szCmdLine = 0x00cf519d "-ddd -window 1280x960", int sw = 0n10)+0x8 [z:\bzflag-dependencies\src\sdl2\src\main\windows\sdl_windows_main.c @ 110] 
08 0019ff04 008532d7 bzflag!invoke_main(void)+0x1e [d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 107] 
09 0019ff60 0085316d bzflag!__scrt_common_main_seh(void)+0x157 [d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288] 
0a 0019ff68 008534b8 bzflag!__scrt_common_main(void)+0xd [d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 331] 
0b 0019ff70 767afcc9 bzflag!WinMainCRTStartup(void)+0x8 [d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_winmain.cpp @ 17] 
0c 0019ff80 76ff809e KERNEL32!BaseThreadInitThunk+0x19
0d 0019ffdc 76ff806e ntdll!__RtlUserThreadStart+0x2f
0e 0019ffec 00000000 ntdll!_RtlUserThreadStart+0x1b
```
![image](https://github.com/user-attachments/assets/8947dee3-de86-48a1-9097-6e1f6e41b632)

**Comment by RighthandSon** [comment]
at the head 2.4 I was able to reproduce and get a similar back trace as @Juesto
on the commit [here](https://github.com/BZFlag-Dev/bzflag/commit/63320f915abab8332187f95408b5747630506c79) I changed the `world` to `_world` and got a slightly different stack trace.

```
#0  0x000055555558fb32 in World::getMaxShots (this=0x0)
    at /home/righthand/GitHub/bzflag/src/bzflag/World.h:312
#1  0x000055555562ec41 in Player::getMaxShots (this=0x555557fa25e0) at Player.cxx:1073
#2  0x000055555562ec70 in Player::addShots (this=0x555557fa25e0, scene=0x555558c8cb30, 
    colorblind=false) at Player.cxx:1079
#3  0x00005555556df327 in drawFrame (dt=0.0362179987) at playing.cxx:6143
#4  0x00005555556e4968 in playingLoop () at playing.cxx:7400
#5  0x00005555556e6b7a in startPlaying (_display=0x5555559bbbf0, renderer=...) at playing.cxx:7890
#6  0x00005555556b767a in main (argc=1, argv=0x7fffffffe518) at bzflag.cxx:1404
```

**Comment by Juesto** [comment]
we determined that reproduction is when aborting downloading files and connecting again
but perhaps take my stacktrace with a pinch of salt because it's possible that its my memory shenanigans causing it. will repro on a known good machine
```
 (6090.49ec): Access violation - code c0000005 (first chance)
eax=0ce925c8 ebx=00310000 ecx=00000001 edx=00000000 esi=0019cbec edi=0019d540
eip=0059fe4f esp=0019cbd8 ebp=0019cbe0 iopl=0         nv up ei pl nz ac pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00210216
bzflag!RemotePlayer::updateShots+0x2f:
0059fe4f 3b91d8020000    cmp     edx,dword ptr [ecx+2D8h] ds:002b:000002d9=????????
0:000> kp
 # ChildEBP RetAddr  
00 0019cbe0 0058b08b bzflag!RemotePlayer::updateShots(float dt = 0.4770747721)+0x2f [z:\bzflag\src\bzflag\remoteplayer.cxx @ 131] 
01 0019d54c 0056f22e bzflag!playingLoop(void)+0xc5b [z:\bzflag\src\bzflag\playing.cxx @ 7302] 
02 0019e71c 0046ecf3 bzflag!startPlaying(class BzfDisplay * _display = 0x00bd51a8, class SceneRenderer * renderer = 0x009ad990)+0x136e [z:\bzflag\src\bzflag\playing.cxx @ 7892] 
03 0019feb8 00855656 bzflag!SDL_main(int argc = 0n3, char ** argv = 0x00aeca10)+0x3273 [z:\bzflag\src\bzflag\bzflag.cxx @ 1404] 
04 0019fee4 008554d8 bzflag!main_getcmdline(void)+0x156 [z:\bzflag-dependencies\src\sdl2\src\main\windows\sdl_windows_main.c @ 80] 
05 0019feec 0085343e bzflag!WinMain(struct HINSTANCE__ * hInst = 0x00400000, struct HINSTANCE__ * hPrev = 0x00000000, char * szCmdLine = 0x00ae5195 "-window 1280x960", int sw = 0n10)+0x8 [z:\bzflag-dependencies\src\sdl2\src\main\windows\sdl_windows_main.c @ 110] 
06 0019ff04 008532d7 bzflag!invoke_main(void)+0x1e [d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 107] 
07 0019ff60 0085316d bzflag!__scrt_common_main_seh(void)+0x157 [d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288] 
08 0019ff68 008534b8 bzflag!__scrt_common_main(void)+0xd [d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 331] 
09 0019ff70 767afcc9 bzflag!WinMainCRTStartup(void)+0x8 [d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_winmain.cpp @ 17] 
0a 0019ff80 76ff809e KERNEL32!BaseThreadInitThunk+0x19
0b 0019ffdc 76ff806e ntdll!__RtlUserThreadStart+0x2f
0c 0019ffec 00000000 ntdll!_RtlUserThreadStart+0x1b
```
![image](https://github.com/user-attachments/assets/fe52e41e-eb37-4b93-bad6-9e3527abe3eb)

**Comment by Juesto** [comment]
I suggest removing the ability to click on connect when a connection is in progress and instead have a cancel button appearing below that.

**Comment by RighthandSon** [comment]
A couple more back traces.
```
#0  0x00005555557b7ba7 in WorldBuilder::unpack (this=0x0, buf=0x5310009c1b39)
    at WorldBuilder.cxx:112
#1  0x00005555557ed585 in loadCachedWorld () at playing.cxx:1841
#2  0x00005555557edc48 in WorldDownLoader::start (this=0x50f00008a3d0, 
    hexDigest=0x50400037ac50 "p027452aa127958dd5f30e3d30fa55b35") at playing.cxx:1881
#3  0x00005555557f28fd in handleServerMessage (human=true, code=30568, len=34, msg=0x7ffff3f00700)
    at playing.cxx:2171
#4  0x0000555555861d89 in playingLoop () at playing.cxx:7480
#5  0x0000555555867e9f in startPlaying (_display=0x504000008990, renderer=...) at playing.cxx:7889
#6  0x00005555557c796a in main (argc=1, argv=0x7fffffffe518) at bzflag.cxx:1404
```

```
#0  0x00005555557b7ba7 in WorldBuilder::unpack (this=0x0, buf=0x7fffdaba2e04)
    at WorldBuilder.cxx:112
#1  0x00005555557ed585 in loadCachedWorld () at playing.cxx:1841
#2  0x00005555557eea07 in WorldDownLoader::finalization (this=0x50f00008a2e0, 
    data=0x5300000f0400 "", length=63255, good=true) at playing.cxx:1918
#3  0x00005555559bcaed in cURLManager::infoComplete (this=0x50f00008a2e0, result=CURLE_OK)
    at cURLManager.cxx:320
#4  0x00005555559bca49 in cURLManager::perform () at cURLManager.cxx:305
#5  0x000055555585c060 in playingLoop () at playing.cxx:7024
#6  0x0000555555867e9f in startPlaying (_display=0x504000008390, renderer=...) at playing.cxx:7889
#7  0x00005555557c796a in main (argc=1, argv=0x7fffffffe518) at bzflag.cxx:1404
```

**Comment by Juesto** [comment]
so, is this fixed for good now?

**Comment by atupone** [comment]
It should, except that the long term solution should be to cleanly close the connection (TCP/UDP), terminating all download, waiting all the messages to be processed, and then start again
